[package]
name = "feed-app"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
opt-level = 'z'
panic = 'abort'

[lib]
crate-type = ["cdylib"]
path = "actor.rs"

[dependencies]
ic-certified-assets = "0.1.0"
ic-cdk = "0.5.0"
ic-cdk-macros = "0.5.0"
candid = "0.7.14"
serde = "1.0.136"